services:
  - type: web
    name: my-bot-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "python3 bot.py"
    envVars:
      - key: DATABASE_URL
        value: your-database-url
      - key: ANOTHER_ENV_VAR
        value: some-value
